name: Setup Grafana Metrics Environment

on:
  workflow_dispatch:

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PROMETHEUS_URL=${{ secrets.PROMETHEUS_URL }}" >> .env
          echo "PROMETHEUS_USER=${{ secrets.PROMETHEUS_USER }}" >> .env
          echo "PROMETHEUS_PASSWORD=${{ secrets.PROMETHEUS_API_KEY }}" >> .env
          echo "GRAFANA_DATASOURCE_NAME=${{ secrets.GRAFANA_DATASOURCE_NAME }}" >> .env
          echo "GRAFANA_API_KEY=${{ secrets.GRAFANA_API_KEY }}" >> .env
          echo ".env file generated for local use or container environment."
